# Define the set of areas that will be analyzed.
areas = {
    "groningen": [
        "Hortusbuurt",
        "Binnenstad",
        "Oosterpoort",
        "Rivierenbuurt",
        "De Wijert",
        "Oosterparkwijk",
        "De Hoogte",
        "Korrewegwijk",
        "Schildersbuurt",
        "Paddepoel",
        "Oranjewijk",
        "Tuinwijk",
        "Selwerd",
        "Vinkhuizen",
        "Hoogkerk-zuid",
        "Gravenburg",
        "De Held",
        "Reitdiep",
        "Hoornse Meer",
        "Corpus den Hoorn",
        "Eemspoort",
        "Euvelgunne",
        "Driebond",
        "Winschoterdiep",
        "Eemskanaal",
        "Helpman",
        "Lewenborg",
        "Beijum",
        "Maarsveld",
    ],
    "drenthe": [
        "Assen Oost",
        "Assen West",
        "Centrum",
        "Kloosterveen",
        "Lariks",
        "Marsdijk",
        "Noorderpark",
        "Peelo",
        "Pittelo",
        "Ter Borch",
    ],
    "friesland": [
        "Achter de Hoven",
        "Aldlân",
        "Bilgaard",
        "Binnenstad en Stationskwartier",
        "Blitsaerd",
        "Buitengebied Noordwest",
        "Camminghaburen",
        "De Hemrik",
        "De Zuidlanden",
        "De Zwette",
        "Heechterp",
        "Hempens, Teerns, en Zuiderburen",
        "Huizum-Oost",
        "Huizum-West",
        "Middelsee",
        "Nijlân",
        "Oranjewijk",
        "Oud Oost",
        "Schepenbuurt",
        "Schieringen en De Centrale",
        "Techum",
        "Vlietzone",
        "Vogelwijk en Componistenbuurt",
        "Vrijheidswijk",
        "Westeinde",
        "Wielenpôlle",
        "Zuiderburen",
    ],
    "flevoland": [
        "Polderwijk",
    ],
    "overijssel": [
        "Baalder",
        "Baalderveld",
        "Berflo Es",
        "Bergweide",
        # "Binnenstad",
        "De Graven Es",
        "De Meijbree",
        "De Riet",
        "De Thij",
        "Groot Driene",
        "Haardijk",
        "Hanzeland",
        "Hasseler Es",
        "Heemsermars",
        "Het Onderdijks",
        "Hofkamp",
        "Ittersum",
        "Keizerslanden",
        "Kloosterlanden",
        "Marslanden",
        "Nieuwe Haven",
        "Nieuwstraatkwartier",
        "Noorderkwartier",
        "OosterDalfsen",
        "Ossenkoppelerhoek",
        "Rivierenwijk",
        "Schelfhorst",
        "Slangenbeek",
        "Sluitersveld",
        "Twekkelerveld",
        "Veerallee",
        "Voorstad",
        "Wierdensehoek",
        "Windmolenbroek",
        "Zandweerd",
    ],
    "noord_holland": [
        "Schrijverswijk",
        "Stad van de Zon",
        "Stadshart",
        "Jordaan",
        "Slotervaart",
        "IJburg",
        "Oostelijke Eilanden",
        "Oostelijk Havengebied",
        "Frederik Hendrikbuurt",
        "Van Lennepbuurt",
        "Da Costabuurt",
        "Kinkerbuurt",
        "Kersenboogerd",
        "Pax",
        "Graan voor Visch",
        "Vrijschot-Noord",
        "Toolenburg",
        "Floriande",
        "Overbos",
        "Bornholm",
        "Beukenhorst-Oost",
        "De Hoek",
        "West",
        "Zuid",
        "Oost",
        "Noord",
        "De President",
        "Graan voor Visch-Zuid",
        "Zuidwijk",
        "Buitenveldert-West",
        "Buitenveldert",
        "Apollobuurt",
        "Stadionbuurt",
        "Prinses Irenebuurt e.o.",
        "Hoofddorppleinbuurt",
        "Willemspark",
        "Schinkelbuurt",
        "Vondelparkbuurt",
        "Helmersbuurt",
        "Overtoomse Sluis",
        "Museumkwartier",
        "Rivierenbuurt",
        "IJselbuurt",
        "Scheldebuurt",
        "Rijnbuurt",
        "De Baarsjes",
        "Landlust",
        "Staatsliedenbuurt",
        "Spaarndammerbuurt",
        "De Pijp",
        "Grachtengordel",
        "Oud-Zuid",
    ],
    "utrecht": [
        "Bedrijventerrein Vathorst",
        "Binnenstad City- En Winkelgebied",
        "Binnenstad Woongebied",
        "Bosgebied",
        "Buitengebied Oost",
        "Calveen",
        "De Berg-Noord",
        "De Berg-Zuid",
        "De Hoef",
        "De Koppel",
        "Dichterswijk, Rivierenwijk",
        "Eemkwartier",
        "Hoogland",
        "Hoogland-West",
        "Hooglanderveen",
        "Isselt",
        "Kanaleneiland",
        "Kattenbroek",
        "Kruiskamp",
        "Leusderkwartier",
        "Liendert",
        "Lombok, Leidseweg",
        "Nederberg",
        "Nieuw Engeland, Schepenbuurt",
        "Nieuwland",
        "Oog in Al",
        "Randenbroek",
        "Rustenburg",
        "Schothorst-Noord",
        "Schothorst-Zuid",
        "Schuilenburg",
        "Soesterkwartier",
        "Stadskern",
        "Terwijde",
        "Vathorst-Centrum",
        "Vathorst-De Laak",
        "Vathorst-De Velden",
        "Veldhuizen",
        "Vermeerkwartier",
        "Zielhorst",
    ],
    "gelderland": [
        "Aldenhof",
        "Altrade",
        "Benedenstad",
        "Biezen",
        "Bijsterhuizen",
        "Bottendaal",
        "Brakkenstein",
        # "Centrum",
        "De Hoop",
        "De Horsten",
        "De Huet",
        "De Kamp",
        "De Pas",
        "Dichteren",
        "Druten-Zuid",
        "Ede-Zuid",
        "Enka",
        "Galgenveld",
        "Goffert",
        "Groenewoud",
        "Grootstal",
        "Hatert",
        "Haven- en industrieterrein",
        "Hazenkamp",
        "Hees",
        "Heideslag",
        "Heijendaal",
        "Hengstdal",
        "Heseveld",
        "Hunnerberg",
        "Kerkenbos",
        "Kernhem",
        "Kortenoord",
        "Kwakkenberg",
        "Lankforst",
        "Lent",
        "Maandereng",
        "Malvert",
        "Meijhorst",
        "Methen",
        "Neerbosch-Oost",
        "Nije Veld",
        "Noordwest",
        "Nude",
        "Oosseld",
        "Oosterhout",
        "Ooyse Schependom",
        "Overstegen",
        "Ressen",
        "Rietkampen",
        "Rijkerswoerd",
        "Roodwilligen",
        "Schöneveld",
        "Staddijk",
        "Stadscentrum",
        "Stadsweiden",
        "Tolhuis",
        "Veldhuizen",
        "Weezenhof",
        "Westkanaaldijk",
        "Wijnbergen",
        "Wolfskuil",
        "Zwanenveld",
    ],
    "zuid_holland": [
        "Afrikaanderwijk",
        "Berkel",
        "Beverwaard",
        "Binnenstad",
        "Bloemendaal",
        "Bloemhof",
        "Bospolder",
        "Buitenhof",
        "Capelle-West",
        "Carnisse",
        "Cool",
        "De Schenkel",
        "Delfshaven",
        "Fascinatio",
        "Feijenoord",
        "Goverwelle",
        "Groente- en Fruitmarkt",
        "Groot-IJsselmonde",
        "Heijplaat",
        "Hellevoet",
        "Het Lage Land",
        "Hillegersberg-Noord",
        "Hillesluis",
        "Hof van Delft",
        "Hoog Dalem",
        "Katendrecht",
        "Kleinpolder",
        "Kleiwegkwartier",
        "Kop van Zuid",
        "Kop van Zuid-Entrepot",
        "Kort Haarlem",
        "Korte Akkeren",
        "Leyenburg",
        "Lombardijen",
        "Middelland",
        "Middelwatering",
        "Moerwijk",
        "Molenlaankwartier",
        "Morgenstond",
        "Nesselande",
        "Nieuw-Helvoet",
        "Nieuw-Mathenesse",
        "Nieuwe Westen",
        "Noord",
        "Noordereiland",
        "Ommoord",
        "Onyx",
        "Oosterflank",
        "Oostgaarde",
        "Oud-Charlois",
        "Oud-IJsselmonde",
        "Oud-Mathenesse",
        "Oude Westen",
        "Overschie",
        "Pendrecht",
        "Plaswijck",
        "Portlandsehoek",
        "Prinsenland",
        "RijswijkBuiten",
        "Rivium",
        "Ruiven",
        "Rustenburg en Oostbroek",
        "Schenkel",
        "Schiebroek",
        "Schieweg",
        "Schollevaar",
        "Spangen",
        "Stadsdriehoek",
        "Stolersluis",
        "Tanthof-Oost",
        "Tanthof-West",
        "Tarwewijk",
        "Transvaalkwartier",
        "Tussendijken",
        "Vogelbuurt",
        "Voordijkshoorn",
        "Voorhof",
        "Vreewijk",
        "Vrijenban",
        "Wateringse Veld",
        "Westergouwe",
        "Westplaat",
        "Westpolder",
        "Wielewaal",
        "Wippolder",
        "Zestienhoven",
        "Zevenkamp",
        "Zuid",
        "Zuiderpark",
        "Zuidwijk",
    ],
    "noord_brabant": [
        "Binnenstad",
        "Brandevoort",
        "Brouwhuis",
        "Dierdonk",
        "Helmond-Noord",
        "Helmond-Oost",
        "Helmond-West",
        "Industriegebied Zuid",
        "Mierlo-Hout",
        "Oosterheide",
        "Rijpelberg",
        "Stiphout",
        "Warande",
        "West",
        "Zuidoost",
    ],
    "limburg": [
        "Blerick-Midden",
        "Blerick-Noord",
        "Blerick-Zuid",
        "Boekend",
        "Centrum",
        "Donderberg",
        "Hoogvonderen",
        "Hout-Blerick",
        "Klingerberg",
        "Lindenheuvel",
        "Maasniel",
        "Maastricht-Centrum",
        "Maastricht-Noordwest",
        "Maastricht-Oost",
        "Maastricht-West",
        "Maastricht-Zuidoost",
        "Meuleveld",
        "Roermond-Oost",
        "Roermond-Zuid",
        "Sanderbout",
        "Vossener",
    ],
    "zeeland": [
        "Binnenstad",
        "Burgh",
        "Haamstede",
        "Lammerenburg",
        "Middelburg-Zuid",
        "Othene",
        "Paauwenburg",
        "Terneuzen-Centrum",
        "Terneuzen-Noord",
        "Terneuzen-West",
        "Terneuzen-Zuid",
        "West-Souburg",
    ],
}
